# Generated by Django 4.2.1 on 2023-05-12 06:27

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Catagury",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("catagury", models.CharField(max_length=50)),
                ("catagury_en", models.CharField(max_length=50)),
                ("img", models.ImageField(upload_to="")),
                ("img_size", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "اقسام الفقرات",
            },
        ),
        migrations.CreateModel(
            name="Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("name_en", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("img", models.ImageField(upload_to="")),
                ("logo_color", models.ImageField(upload_to="")),
                ("logo_white", models.ImageField(upload_to="")),
                ("logo_black", models.ImageField(upload_to="")),
                ("phoneNumber", models.PositiveIntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("location", models.CharField(max_length=500)),
                ("TimeOfWork", models.CharField(max_length=100)),
                ("YearsOfExperience", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "معلومات المكتب",
            },
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=50)),
                ("keyword_en", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="NavLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("name_en", models.CharField(max_length=20)),
                ("url", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "روابط الشريط العلوي",
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("title_en", models.CharField(max_length=500)),
                ("description", models.CharField(max_length=1000)),
                ("description_en", models.CharField(max_length=1000)),
                ("img", models.ImageField(upload_to="")),
                ("is_page", models.BooleanField(default=False)),
                ("post", ckeditor_uploader.fields.RichTextUploadingField()),
                ("post_en", ckeditor_uploader.fields.RichTextUploadingField()),
                (
                    "catagury",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.catagury"
                    ),
                ),
                ("keywords", models.ManyToManyField(to="core.keyword")),
            ],
        ),
    ]
