# Generated by Django 4.2.1 on 2023-05-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_emaillist_order_project_quicklink_sociallink_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="catagury",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="img_project",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="information",
            name="keyword",
            field=models.ManyToManyField(blank=True, null=True, to="core.keyword"),
        ),
        migrations.AddField(
            model_name="keyword",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="navlink",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quicklink",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sociallink",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
