# Generated by Django 4.2.1 on 2023-05-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_article_active_catagury_active_img_project_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="keywords",
            field=models.ManyToManyField(blank=True, to="core.keyword"),
        ),
        migrations.AlterField(
            model_name="information",
            name="keyword",
            field=models.ManyToManyField(blank=True, to="core.keyword"),
        ),
    ]
