# Generated by Django 4.2.1 on 2023-05-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_article_keywords_alter_information_keyword"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"verbose_name": "الفقرات"},
        ),
        migrations.AlterModelOptions(
            name="quicklink",
            options={"verbose_name": "روابط الشريط السفلي"},
        ),
        migrations.AlterField(
            model_name="navlink",
            name="url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
