# Generated by Django 4.2.1 on 2023-05-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_article_options_alter_quicklink_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="catagury",
            name="head",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="catagury",
            name="head_en",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
